### ISSUE TITLE
Having troubles loading the dataset

### ISSUE THREAD

**Issue by zihaohe123** [ldzhangyx/BART-fusion#2]
Hi Yixiao,

When I was trying to load your dataset with pickle using the following code
_x = pickle.load(open('dataset_full_256.pkl', 'rb'))_
it gave me such an error
_ModuleNotFoundError: No Module named "mymodel"_

Seems the saved pickle file has some instances of class.  Any idea how to fix this? Or could you just publish the raw unstructured data? Thanks!

Best,
Zihao

**Comment by ldzhangyx** [comment]
Hi, I have changed the code. In this case we import `mymodel` is to import the `LyricsCommentData` class. I have provided this file so you can use it to analyse the dataset pkl file.

**Comment by zihaohe123** [comment]
thanks! that's really helpful!

**Comment by Wang-Haining** [comment]
Hi,

I still have a hard time in opening the pkl. I hacked the code a little bit but still didn't work it out. The error reads "ModuleNotFoundError: No module named 'mymodel.LyricsCommentData'; 'mymodel' is not a package." I wonder if it is possible to release raw text data. Thanks.

**Comment by ldzhangyx** [comment]
@Wang-Haining Please check https://zenodo.org/record/7429711. I have published a json version.

**Comment by Wang-Haining** [comment]
Great, thanks a lot!

**Comment by Wang-Haining** [comment]
Hi, could you provide train/val indices for the json version? Thanks!

**Comment by ldzhangyx** [comment]
@Wang-Haining I use the random seed of 42. Please use this to split dataset.

**Comment by Wang-Haining** [comment]
> @Wang-Haining I use the random seed of 42. Please use this to split dataset.

Appreciate your answer. I think full reproducibility and a fair comparison require a dataset with frozen splits.

**Comment by ldzhangyx** [comment]
@Wang-Haining Thanks for your reply. The reported results are the average of 3 different splits as I described in the paper (for paired t-test), but I did not actually save the split during each experiment. I feel so sorry for the inconvenience. If you want to reproduce our model as the baseline, I recommend using our pretrained checkpoints instead.

**Comment by Wang-Haining** [comment]
> @Wang-Haining Thanks for your reply. The reported results are the average of 3 different splits as I described in the paper (for paired t-test), but I did not actually save the split during each experiment. I feel so sorry for the inconvenience. If you want to reproduce our model as the baseline, I recommend using our pretrained checkpoints instead.

Thanks! That makes quite sense. BTW, I really enjoy your paper, great work!
