### ISSUE TITLE
Music encoder checkpoint?

### ISSUE THREAD

**Issue by zihaohe123** [ldzhangyx/BART-fusion#3]
Hi,

Could you share the checkpoint of the music encoder? Thanks!

**Comment by ldzhangyx** [comment]
Hi, you can download the checkpoints at https://drive.google.com/drive/folders/18EUUx-KT9xGJ1uq2UoOgj0X9BpngNn_T?usp=sharing.

**Comment by zihaohe123** [comment]
Thanks a lot!
